const path = require("path");
require("dotenv").config({
  path: path.join(__dirname, "../.env"),
});

const {
  HTTP_PORT,
  STATIC_FOLDER,
  CLIENT_URL,
  SERVER_URL,
  EMAIL_CC,
  EMAIL_SENDER_ADDRESS,
  EMAIL_SENDER_PASSWORD,
  EMAIL_HOST,
  GITHUB_API_TOKEN,
  TWITTER_API_TOKEN,
  GOOGLE_SHEETS_SUBSCRIBE_SHEET_ID,
  GOOGLE_SHEETS_EMAIL,
  GOOGLE_SHEETS_PRIVATE_KEY,
} = process.env;

module.exports = {
  HTTP_PORT,
  STATIC_FOLDER,
  CLIENT_URL,
  SERVER_URL,
  EMAIL_CC,
  EMAIL_SENDER_ADDRESS,
  EMAIL_SENDER_PASSWORD,
  EMAIL_HOST,
  GITHUB_API_TOKEN,
  TWITTER_API_TOKEN,
  GOOGLE_SHEETS_SUBSCRIBE_SHEET_ID,
  GOOGLE_SHEETS_EMAIL,
  GOOGLE_SHEETS_PRIVATE_KEY: GOOGLE_SHEETS_PRIVATE_KEY.replace(
    /\\n/g,
    "\n"
  ).trim(),
};
