require("dotenv").config();

const {
  HTTP_PORT,
  STATIC_FOLDER,
  SITE_URL = "https://danielstarns.com",
  EMAIL_CC,
  EMAIL_SENDER_ADDRESS,
  EMAIL_SENDER_PASSWORD,
  EMAIL_HOST,
  GITHUB_API_TOKEN,
  TWITTER_API_TOKEN,
} = process.env;

module.exports = {
  HTTP_PORT,
  STATIC_FOLDER,
  SITE_URL,
  EMAIL_CC,
  EMAIL_SENDER_ADDRESS,
  EMAIL_SENDER_PASSWORD,
  EMAIL_HOST,
  GITHUB_API_TOKEN,
  TWITTER_API_TOKEN,
};
